name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.x"]
    steps:
    - name: Setup FFmpeg
      uses: AnimMouse/setup-ffmpeg@v1
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        cache: 'pip'
        python-version: ${{ matrix.python-version }}
    - name: Install virtualenv
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade virtualenv
    - name: Install dependencies
      run: |
        make develop
    - name: Run tests
      run: |
        make test
    - name: Coveralls
      uses: AndreMiras/coveralls-python-action@develop
      with:
        parallel: true
        flag-name: Test
  coveralls_finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: AndreMiras/coveralls-python-action@develop
      with:
        parallel-finished: true
